apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain # Keeps the EBS volume even if PVC is deleted (data safe!).
volumeBindingMode: WaitForFirstConsumer # Delays volume creation until a Pod is scheduled (ensures AZ matching)


# eks-csi-driver
# kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.41"
