apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense-4
  region: us-east-1

managedNodeGroups:
  - name: Expense
    instanceTypes: ["m5.large","c3.large","c4.large","c5.large","c5d.large"]
    desiredCapacity: 3
    spot: true 