apiVersion: v1
kind: Pod
metadata:
 name: multi-cont
 namespace: name-space-01

spec:
  containers:
  - name: nginx
    image: nginx

  - name: almalinux
    image: almalinux:8
    command: ["sleep", "2000"]
