kind: Pod
apiVersion: v1
metadata:
  name: web-np
  labels:
    name: web
    connection: https
    secure: almost
    evidence: ofcourse
    service: node-port
spec:
  containers:
  - name: web-server
    image: nginx
---

kind: Service
apiVersion: v1
metadata:
  name: NodePort
spec:
  type: NodePort
  selector:
    name: web
    connection: https
    secure: almost
    evidence: ofcourse
    service: node-port

  ports:
  - protocol: TCP  
    port: 80
    targetPort: 80  
    nodePort: 29000