apiVersion: v1
kind: Pod

metadata:
 name: web
 labels:
  ci-cd: "continues integ tool"
  k8s: "orchestration"

spec:
  containers:
    - name: web-server
      image: nginx
      env:
      - name: "hdcontainers"
        value: "2000"
      - name: "images"
        value: "20"
# 1000m is equal to 1 processor or 1 process
      resources: 
       requests:
        memory: "64Mi"
        cpu: "250m"
       limits:
         memory: "500Mi"
         cpu: "500m"




  
    