apiVersion: v1
kind: Pod

metadata:
 name: web
 labels:
  ci-cd: "continuesintegool"
  k8s: "orchestration"

spec:
  containers:
    - name: web-server
      image: nginx
      env:
      - name: "hdcontainers"
        value: "2000"
      - name: "images"
        value: "20"
# 1000m is equal to 1 processor or 1 process
      resources: 
       requests:
        memory: "10Mi"
        cpu: "25m"
       limits:
         memory: "50Mi"
         cpu: "200m"




  
    