kind: Pod
apiVersion: v1
metadata:
  name: web-pod
  labels:
    name: web
    connection: https
    secure: almost
    evidence: ofcourse
spec:
  containers:
  - name: web-server
    image: nginx
---

kind: Service
apiVersion: v1
metadata:
  name: loadbalancer
spec:
  selector:
    name: web
    connection: https
    secure: almost
    evidence: ofcourse

  ports:
  - protocol: tcp
    port: 80
    targetPort: 80  


  
