apiVersion: v1
kind: Pod
metadata:
  name: ebs-static
  labels:
    name: web
    service: pv
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1d
  containers:
  - name: nginx
    image: joindevops/frontend:1.2.0 
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-static

---

kind: Service
apiVersion: v1
metadata:
  name: loadbalancer
spec:
  type: LoadBalancer
  selector:
    name: web
    service: pv

  ports:
  - protocol: TCP  
    port: 80
    targetPort: 80  
    nodePort: 30124