apiVersion: v1
kind: Pod
metadata:
  name: ebs-static
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: ebs-static
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-static-pvc