apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels: 
    app: web
    type: nginx
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: web
      type: nginx
  template:
    metadata:
      labels:
        app: web
        type: nginx
    spec:
      containers:
      - name: frontend
        image: {{ .Values.deployment.image }}
        ports: 
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    app: web
    type: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.loadbalancer.targetPort }}
