apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-statefull
  namespace: expense
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-090242ff24538c289
