apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-statefull
  namespace: expense
spec: 
  storageClassName: ""
  volumeName: ebs-statefull
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi