apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    app: frontend
    type: nginx
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      type: nginx
      project: expense
  template:
    metadata:
      labels:
        app: frontend
        type: nginx
        project: expense
    spec:
      containers:
      - name: nginx
        image: joindevops/frontend:1.2.0 
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    app: frontend
    type: nginx
    project: expense
  ports:
  - protocol: TCP 
    port: 80
    targetPort: 80

    
        
      