apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    type: nodejs
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      type: nodejs
      project: expense
  template:
    metadata:
      labels:
        app: backend
        type: nodejs
        project: expense
    spec:
      containers:
      - name: backend
        image: joindevops/backend:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    app: backend
    type: nodejs
    project: expense
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    

        
      