apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
   type: app
spec:
  replicas: 2
  selector:
    matchLabels:
      type: app
  template:
    metadata:
      labels:
        type: app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: name
                operator: in
                values:
                - ul
              
      containers: 
      - name: nginx
        image: lakshmikanth333/app3:4.1
        ports:
        - containerPort: 80
      tolerations:
      - key: type
        operator: Equal
        value: hardware
        effect: NoExecute