apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    type: web
spec:
  nodeSelector:
    fuck: sake
  containers:
  - name: web
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: gun
spec:
  affinity:
    podAffinity: # Use podAntiAffinity for pod antifinity ( and everything is same)
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: fuck
              operator: In 
              values:
              - sake
      topologyKey: topology.kubernetes.io/zone
  containers:
    name: web
    image: nginx

