apiVersion: v1
kind: Pod
metadata:
  name: efs-dynamic
  labels:
    purpose: "efs-static-provision"
spec:
  containers: 
  - name: nginx
    image: nginx
    volumeMounts: 
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes: 
  - name: persistent-storage
    PersistentVolumeClaim: 
      claimName: efs-dynamic
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec: 
  type: LoadBalancer
  selector: 
    purpose: "efs-dynamic-provision"
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 3007