apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: efs-dynamic
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "efs-expense"
  # volumeName: "efs-static" --> No volume name here
  resources:
    requests:
      storage: 5Gi