apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    type: nodejs
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: backend
      type: nodejs
  template:
    metadata:
      labels:
        app: backend
        type: nodejs
    spec: 
      containers:
      - name: backend
        image: {{ .Values.deployment.image }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    app: backend
    type: nodejs
  ports:
  - protocol: TCP
    port: 8080
    targetPort: {{ .Values.service.targetPort }}
