apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec: 
  storageClassName: "ebs-sc"
  accessModes:
  - ReadWriteOnce
  resources:
    requests: 
      storage: 19Gi
---

apiVersion: v1
kind: Pod
metadata:
  name: ebs-dynamic
  labels:
    purpose: "ebs-dynamic-prov"
spec:
# Here the given region us-east-1d node only gets the pv volume since we given it
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1b
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
# this is the mount directory for our 20Gi persistent volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-dynamic

--- 

kind: Service
apiVersion: v1
metadata:
  name: nginx-dynamic
spec:
  type: LoadBalancer
  selector:
    purpose: "ebs-dynamic-prov"
  ports:
  - protocol: TCP  
    port: 80
    targetPort: 80  
    nodePort: 3007