apiVersion: v1
kind: PerstistentVolumeClaim
metadata: 
  name: efs-static
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  volumeName: efs-static
  resources:
    requests:
      storage: 5Gi


